# Реализации классов билдера для первой части задачи - для абстрактных операций.
from .v0_abstract_builder import AbstractObservationBuilderSequencePrediction
from .v0_abstract_builder import AbstractObservationBuilderCloseSignal
from .v0_abstract_builder import AbstractObservationBuilderOpenSignal
from .v0_abstract_builder import AbstractObservationBuilderCompleteTrade

from .v1_basic import ObservationBuilderBasic
from .v1_basic import ObservationBuilderBasicMultiRate
from .v1_basic import ObservationBuilderBasicMultiRateSeparate
from .v1_with_trend_indicator import ObservationBuilderTrendIndicator

from .v3_orderbook_volumes import ObservationBuilderOrderbookTradeBalance

from .v4_opposite_trades import ObservationBuilderOrderbookTradeBalance


